services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - banco-crud-cadastro:/var/lib/mysql

volumes:
  banco-crud-cadastro:
    external: true